<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
    public function findNumberTicketOneDate($date)
    {


      $qb = $this->createQueryBuilder('b');
        $qb
            ->where('b.date = :date')
            ->setParameter('date', $date);
        $findNumberTicketOneDate = $qb->getQuery()->getScalarResult();
        return count($findNumberTicketOneDate);
    }

}

