<?php

namespace AppBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
   /* public function getInformationWithBooking()
    {
        $qb = $this
            ->createQueryBuilder('i')
            ->leftJoin('i.booking', 'book')
            ->addSelect('book')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }*/
}
