<?php

namespace AppBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{

    public function findNames()
    {
        $qb = $this->createQueryBuilder('i');
        $qb
            ->where('i.name = :name');
        $qb->getQuery();

        return $qb;
    }
}
